#!/usr/bin/env ruby

ORG = "gilt"
server = "http://localhost:9000"

all = {
  "apidoc" => {
    "ruby_client" => "lib/apidoc-cli/com_gilt_apidoc_v0_client.rb"
  }
}

all.each do |project, data|
  data.each do |target, path|
    cmd = "curl --silent #{server}/#{ORG}/#{project}/latest/#{target} > #{path}"
    puts cmd
    system(cmd)
  end
end
